---

- name: 'Set up Envoy directories'
  file:
    group: root
    mode: '0755'
    owner: root
    path: '{{ envoy_etc_dir }}'
    state: directory
  become: true
  tags: ct-envoy

- name: 'Set sysctl for max files'
  copy:
    dest: /etc/sysctl.d/50-skew-maxfiles.conf
    group: root
    mode: '0644'
    owner: root
    src: sysctl-maxfiles.conf
  become: true
  tags: ct-envoy

- name: 'Set limits.d max files'
  template:
    dest: /etc/security/limits.d/90-skew-nofiles.conf
    group: root
    mode: '0644'
    owner: root
    src: limits-nofiles.conf.j2
  notify: handler_reload_systemd
  become: true
  tags: ct-envoy

- name: 'Generate Lets Encrypt certificate'
  command: /usr/bin/letsencrypt certonly -n --standalone --agree-tos -m {{ envoy_email_addr }} -d {{ item.fqdn }}
  args:
    creates: /etc/letsencrypt/live/{{ item.fqdn }}/fullchain.pem
  loop: '{{ envoy_listeners }}'
  when: envoy_generate_certificate
  become: true
  tags: ct-envoy

- name: 'Render Envoy config file'
  template:
    backup: true
    dest: '{{ envoy_etc_dir }}/envoy.yaml'  # must be .yaml
    group: root
    owner: root
    src: envoy_edge_proxy.yml.j2
  notify: handler_restart_envoy
  become: true
  tags: ct-envoy

...
