---
# --------------------------------

- name: 'Install some packages so we can install the repo key'
  ansible.builtin.apt:
    name: '{{ envoy_dependencies }}'
    state: present
  become: true
  tags: ["ct-envoy"]

- name: 'Add Envoy repo key'
  ansible.builtin.apt_key:
    url: 'https://getenvoy.io/gpg'
    validate_certs: true
    state: present
  become: true
  tags: ["ct-envoy"]

- name: 'Add Envoy repository to APT'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb {{ ct_codename }} stable'
    state: present
    update_cache: true
    filename: envoy
  register: reg_envoy_repo
  become: true
  tags: ["ct-envoy"]

- name: 'Update APT cache and install Envoy'
  ansible.builtin.apt:
    name: '{{ envoy_packages }}'
    update_cache: '{{ reg_envoy_repo is changed }}'
    state: present
  become: true
  tags: ["ct-envoy"]

- name: 'Create systemd unit file for Envoy'
  ansible.builtin.template:
    src: envoy.service.j2
    dest: /etc/systemd/system/{{ envoy_service }}
    owner: root
    group: root
    mode: '0644'
  register: reg_service
  become: true
  tags: ["ct-envoy"]

- name: 'Set Envoy service to {{ envoy_state }}'
  ansible.builtin.systemd:
    name: '{{ envoy_service }}'
    state: '{{ envoy_state }}'
    enabled: true
    daemon_reload: '{{ reg_service is changed }}'
  become: true
  tags: ["ct-envoy"]

# --------------------------------
...
