---
# --------------------------------

- name: "Install some packages so we can install the repo key"
  ansible.builtin.apt:
    name: "{{ envoy_dependencies.debian }}"
    state: present
  become: true
  tags: ["ct-envoy"]

- name: "Add Envoy repo key"
  ansible.builtin.apt_key:
    keyring: "{{ envoy_repo.debian.keyring }}"
    state: present
    validate_certs: true
    url: "{{ envoy_repo.debian.key }}"
  become: true
  tags: ["ct-envoy"]

- name: "Add Envoy repository to APT"
  ansible.builtin.apt_repository:
    filename: getenvoy
    repo: "deb [arch=amd64 signed-by={{ envoy_repo.debian.keyring }}] {{ envoy_repo.debian.url }} {{ ct_codename }} main"
    state: present
    update_cache: true
  register: reg_envoy_repo
  become: true
  tags: ["ct-envoy"]

- name: "Update APT cache and install Envoy"
  ansible.builtin.apt:
    name: "{{ envoy_packages.debian }}"
    update_cache: "{{ reg_envoy_repo is changed }}"
    state: present
  become: true
  tags: ["ct-envoy"]

# --------------------------------
...
