---
#
- name: 'install some packages so we can install the repo key'
  apt:
    name: '{{envoy_dependencies}}'
    state: present
  become: true
  tags:
  - ct-envoy

- name: 'add Envoy repo key'
  apt_key:
    url: 'https://getenvoy.io/gpg'
    validate_certs: true
    state: present
  become: true
  tags:
  - ct-envoy

- name: 'add Envoy repository to APT'
  apt_repository:
    repo: 'deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb {{ct_codename}} stable'
    state: present
    update_cache: true
    filename: envoy
  register: reg_envoy_repo
  become: true
  tags:
  - ct-envoy

- name: 'update APT cache and install Envoy'
  apt:
    name: '{{envoy_packages}}'
    update_cache: '{{reg_envoy_repo is changed}}'
    state: present
  become: true
  tags:
  - ct-envoy

- name: 'create systemd unit file for Envoy'
  template:
    src: envoy.service.j2
    dest: /etc/systemd/system/{{envoy_service}}
    owner: root
    group: root
    mode: '0644'
  register: reg_service
  become: true
  tags:
  - ct-envoy

- name: 'set Envoy service to {{envoy_state}}'
  systemd:
    name: '{{envoy_service}}'
    state: '{{envoy_state}}'
    enabled: true
    daemon_reload: '{{reg_service is changed}}'
  become: true
  tags:
  - ct-envoy
...
