---
- name: "Handler_Restart_Envoy"
  ansible.builtin.systemd:
    state: restarted
    name: envoy
  become: true

- name: "Handler_Restart_Datadog_For_Envoy"
  ansible.builtin.systemd:
    state: restarted
    name: "datadog-agent"
  become: true

- name: "Handler_Reload_Systemd"
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
...
